"""ajout champs status

Revision ID: 83e73af762e2
Revises: 
Create Date: 2024-06-23 17:03:31.752724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e73af762e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###
    # Mettre à jour la colonne pour la rendre NOT NULL avec une valeur par défaut
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.String(length=10), nullable=False, server_default='user')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
